M48
; DRILL file {KiCad (6.0.7)} date Fri Aug 12 15:34:31 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-12T15:34:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0512
%
G90
G05
T1
X4.2974Y-2.6081
X4.4388Y-2.4667
X4.4388Y-2.6081
T2
X4.2974Y-2.4667
T0
M30
